name: Bayes-Net-UnitTests

on:
  pull_request:
    paths:
      - "bayes-net/**"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run tests
        run: python -m unittest main
        working-directory: ./bayes-net
