name: Search-UnitTests

on:
  pull_request:
    paths:
      - "search/**"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Run tests
        run: python runner.py
        working-directory: ./search
